### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Buhrbuhr** [BSData/frostgrave#44]
Hi. I'd like to join, learn how to update the FG rep and then help contribute to it. 

Cheers
Florian

**Comment by Vescarea** [comment]
Welcome! Sorry for the latereply. So the current state the files no longer work like they should due to battlescribe having a big update some time ago, my best advice is to start from scratch and replicate the template i used. If your wondering why stuff had cost of -90000000 etc it was because the old version wouldnt let me have an unlimited - cost and the list worked on taking off gold/ points rather than adding them.
I can explain to you how i got most of the leveling elements etc but the vault id have to look in to it again.
I wouldnt attempt to copy anything over from the list as it gave me some trouble before when trying to make a new version.
But see what you can come up with and load it straight up and remove/ replace the old versions.

Thanks
Ves

**Comment by Rylen27** [comment]
wish you guys luck fixing or updating the BSdata for Frostgrave. It is truly awesome when it works. I wish we had an updated version with all the newer books to use too and I understand why this is a huge job to do probono. Unfortunately I am not a programmer and 2nd edition is coming out in August, but there truly is not anything else to use that is even close to being fully compatible with all the books.

**Comment by Vescarea** [comment]
> wish you guys luck fixing or updating the BSdata for Frostgrave. It is truly awesome when it works. I wish we had an updated version with all the newer books to use too and I understand why this is a huge job to do probono. Unfortunately I am not a programmer and 2nd edition is coming out in August, but there truly is not anything else to use that is even close to being fully compatible with all the books.

Thanks for kind words Im glad people enjoyed using it in the last version of battlscribe, I've recently re-done the Judge Dredd ministures game for the older rules edition and have picked up some new tricks for when i can get back to Frostgrave. The one thing im happy is the no minimum cost :). I am happy to talk through with anyone if they are interested in how it all used to work.

Thanks
Ves

**Comment by amis92** [comment]
Closing due to no @Buhrbuhr response.
